using System;
using System.Collections.Generic;
using System.Text;

namespace SpacePi.Dashboard.Analyzer.Binding {
    /// <summary>
    /// A class generated by this generator
    /// </summary>
    public record GeneratedClass {
        /// <summary>
        /// A nonce used to generate unique class names
        /// </summary>
        private static int Nonce = 0;

        /// <summary>
        /// The namespace to generate code in
        /// </summary>
        public static readonly string Namespace = $"{nameof(SpacePi)}.{nameof(Dashboard)}.{nameof(Analyzer)}.{nameof(Binding)}.Generated";
        /// <summary>
        /// The name of the class to generate
        /// </summary>
        public readonly string ClassName = $"G{Nonce++:D7}";
    }
}
