#include <spacepi/resource/ADC.hpp>
#include <spacepi/resource/BusTransaction.hpp>
#include <spacepi/resource/DigitalIO.hpp>
#include <spacepi/resource/I2C.hpp>
#include <spacepi/resource/Memory.hpp>
#include <spacepi/resource/Processor.hpp>
#include <spacepi/resource/ResourceFactory.hpp>
#include <spacepi/resource/ResourcePtr.hpp>
#include <spacepi/resource/SPI.hpp>
#include <spacepi/resource/UART.hpp>
