set(globs)
string(REPLACE "," ";" ext_list ${exts})
message("Exts: ${exts}")
message("Exts: ${ext_list}")
foreach (ext IN LISTS ext_list)
    list(APPEND globs "${root_dir}/*.${ext}")
endforeach()
message("Globs: ${globs}")
file(GLOB_RECURSE files ${globs})
foreach (file IN LISTS files)
    if (${comp_file} IS_NEWER_THAN ${file})
        file(REMOVE ${file})
    endif()
endforeach()
